### ISSUE TITLE
Add Modulith component diagrams

### ISSUE THREAD

**Issue by odrotbohm** [st-tu-dresden/videoshop#120]

**Comment by martinmo** [comment]
Shall I create another issue to track the work needed to replace the MagicDraw exported diagrams in the developer documentation with the ones generated by Modulith? Or do you want to do that as part of this issue?

**Comment by odrotbohm** [comment]
I'd love to prepare a Modulith release first so that we get the automatic naming and the callbacks for proper coloring into the dependency we use and not have to depend on snapshots. I'd merge the feature branch then so that the diagrams are generated in the first place. We can then have a separate ticket for a revamp of the developer documentation including the generated diagrams.

**Comment by odrotbohm** [comment]
That's merged now. Generated diagrams can be found in `target/generated-docs/moduliths`.
