### ISSUE TITLE
Upgrade to new lab starter

### ISSUE THREAD

**Issue by odrotbohm** [st-tu-dresden/videoshop#157]
- [x] Upgrade build to Java 17
- [x] Remove obsolete starters for validation and Thymeleaf layout dialect
- [x] Upgrade to Salespoint 8.0

**Comment by martinmo** [comment]
The Github Action fails because of an old JDK, I'll fix this.

**Comment by martinmo** [comment]
It still fails, but because of maven-javadoc-plugin, but that's another issue :)
