### ISSUE TITLE
Error submitting the registration form

### ISSUE THREAD

**Issue by pha-Z** [st-tu-dresden/videoshop#70]
When trying to register (http://localhost:8080/register), following error gets thrown:

There was an unexpected error (type=Internal Server Error, status=500).
Failed to instantiate [videoshop.customer.RegistrationForm]: Specified class is an interface

error was produced with the following:

Name: abc
Passwort: 1234
Adresse: adresse

**Comment by AES-256-GCM** [comment]
Same problem :(

**Comment by olivergierke** [comment]
Workaround is to remove `@ModelAttribute` from `CustomerController.registerNew(…)`.
