### ISSUE TITLE
Command line inputs in readme should be without "$"

### ISSUE THREAD

**Issue by PhilippMatthes** [st-tu-dresden/videoshop#85]
For convenience Purposes, the shown command line inputs in the README should be without the `$` symbol, so they can be copied and pasted without inconvenience.

**Comment by PhilippMatthes** [comment]
Additionally, I understand that the `$` symbols are there to represent what's input and output. I'd appreciate an open discussion if needed.

**Comment by odrotbohm** [comment]
That's an interesting request. I was assuming you'd copy the commands line by line to see the actual output. I am not even sure you could copy them en bloc and they'd properly execute.

Another reason I'd actually like to keep it that way is that we *want* students to execute them line by line. As they should familiarize themsleves with what's happening in a particular step. Copy them in one go and just throwing them into a command line kind of defeats that idea.

WDYT?

**Comment by PhilippMatthes** [comment]
I see your point, but I'd like to give another opinion. the typical student (as I imagine him) wouldn't care about which commands are popping up in the command line, neither would he try to understand the commands. In the end, you are showing the command lines for convenience purposes, so the students don't have to look them up themselves.

**Comment by martinmo** [comment]
IMHO, optimizing the README for lazy students is not a good idea. The "barrier" to copy and paste the lines individually is actually a feature and has a learning effect.

**Comment by odrotbohm** [comment]
I am with Martin here. We acknowledge the way students might approach that but the idea basically is to guide them along but maybe making it slightly inconvenient to – by that – maybe trigger a "Oh, what is that actually doing?".

What the individual statements do should actually be clear from the lectures of last semester, it's more about realizing what the procedure looks like: checkout, switch to the project directory, build, run. And I think listing the commands the way we currently do is a good compromise here.
